language: emacs-lisp
sudo: no
env:
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.3-travis
  - EVM_EMACS=emacs-27.1-travis
#   - EVM_EMACS=emacs-git-snapshot-travis
script:
  - emacs -Q --batch --load dtrt-indent.el --load dtrt-indent-test.el
